<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-02-21 14:03

from django.db import migrations, models
=======
# Generated by Django 4.0.2 on 2022-02-23 16:35

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 2b39425 (rewrite models 2)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('status', models.BooleanField(default=False)),
                ('supervisor', models.CharField(max_length=25)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('admin', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=150)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('role', models.CharField(choices=[('F', 'Front-End'), ('B', 'Back-End')], max_length=15)),
            ],
            options={
                'verbose_name': 'Разработчик',
                'verbose_name_plural': 'Разработчики',
=======
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lname', models.CharField(max_length=25)),
                ('Fname', models.CharField(max_length=25)),
                ('role', models.CharField(choices=[('F', 'Front-End'), ('B', 'Back-End'), ('FS', 'Full-Stack')], max_length=15)),
            ],
            options={
                'verbose_name': 'Разработчик',
                'verbose_name_plural': 'Разработчики',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lname', models.CharField(max_length=25)),
                ('Fname', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
>>>>>>> 2b39425 (rewrite models 2)
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=50)),
                ('project', models.ManyToManyField(to='main.Projects')),
=======
                ('title_task', models.CharField(blank=True, max_length=50)),
>>>>>>> 2b39425 (rewrite models 2)
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('status', models.BooleanField(default=False)),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField(auto_now_add=True)),
                ('developers', models.ManyToManyField(related_name='developer', to='main.Developers')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.supervisor')),
                ('task', models.ManyToManyField(to='main.Tasks')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250, verbose_name='Текст')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='main.projects', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'Коммент',
                'verbose_name_plural': 'Комментарии',
            },
        ),
>>>>>>> 2b39425 (rewrite models 2)
    ]
