# Generated by Django 4.0.2 on 2022-03-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tasks_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='count_procents_done',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
